### ISSUE TITLE
Fix AssetFix on J315

### ISSUE THREAD

**Issue by sovainfo** [elinw/AssetFix#2]
Ran into the problem of unknown  JObservableInterface, the only workaround that worked was add require_once JPATH_CONFIGURATION.'/libraries/joomla/observer/mapper.php'; to table.php

Changed the code for Articles. No need to fix what is not broken. Checked for asset_id to be correct and only update when not.
Added notification of update
Tried to use $contenttable to update, but that doesn't work in this context.

[code]              foreach ($articles as $article)
                {
                    $asset->id = 0;
                    $asset->reset();

```
                // We're going to load the articles by asset name.
                if ($article->id > 0)
                {
                    $asset->loadByName('com_content.article.' . (int) $article->id);
                    if ($asset->id != $article->asset_id) {
                        $query = $this->_db->getQuery(true);
                        $query->update($this->_db->quoteName('#__content'));
                        $query->set($this->_db->quoteName('asset_id') . ' = ' . (int) $asset->id);
                        $query->where('id = ' . (int) $article->id);
                        $this->dbo->setQuery($query);
                        $this->dbo->query(); 

                        // Code below doesn't update the asset_id !???
                        // $contenttable->reset();
                        // $contenttable->load($article->id);
                        // $contenttable->asset_id = (int) $asset->id;
                        // $contenttable->store();

                        $this->appendBody('<p>Article:' . $article->title . ' Asset: ' . $asset->id . ":" . $asset->name);
                    }
                }                   
            }

            $this->appendBody('<p>Article assets successfully finished.</p>');
```

[/code]

**Comment by elinw** [comment]
That should be working now, the main thing is to include the cms and legacy files when bootstrapping. 
That is actaully the base problem which required the hotfix linked in the docs.joomla.org wiki relating to stand alone applications.

**Comment by sovainfo** [comment]
As mentioned on the forum I tried and still receive that error.

**Comment by sovainfo** [comment]
Can confirm it works now after the fix with IS_MAC.

Too bad you didn't implement my changes!
